# Generated by Django 3.1.5 on 2021-01-17 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sync_db', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commissiezetelvastpersoon',
            name='commissie',
        ),
        migrations.RemoveField(
            model_name='commissiezetelvastvacature',
            name='commissie',
        ),
        migrations.RemoveField(
            model_name='commissiezetelvervangerpersoon',
            name='commissie',
        ),
        migrations.RemoveField(
            model_name='commissiezetelvervangervacature',
            name='commissie',
        ),
        migrations.AddField(
            model_name='commissiezetelvastpersoon',
            name='commissie_zetel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sync_db.commissiezetel'),
        ),
        migrations.AddField(
            model_name='commissiezetelvastvacature',
            name='commissie_zetel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sync_db.commissiezetel'),
        ),
        migrations.AddField(
            model_name='commissiezetelvervangerpersoon',
            name='commissie_zetel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sync_db.commissiezetel'),
        ),
        migrations.AddField(
            model_name='commissiezetelvervangervacature',
            name='commissie_zetel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sync_db.commissiezetel'),
        ),
    ]
