# Generated by Django 3.1.5 on 2021-01-17 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sync_db', '0002_auto_20210117_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commissiezetelvastvacature',
            name='persoon',
        ),
        migrations.RemoveField(
            model_name='commissiezetelvervangervacature',
            name='persoon',
        ),
        migrations.AddField(
            model_name='commissiezetelvastvacature',
            name='fractie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sync_db.fractie'),
        ),
        migrations.AddField(
            model_name='commissiezetelvervangervacature',
            name='fractie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sync_db.fractie'),
        ),
    ]
