# Generated by Django 3.0.6 on 2020-06-01 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_db', '0002_auto_20200601_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zaak',
            name='citeer_titel',
        ),
        migrations.AddField(
            model_name='zaak',
            name='citeertitel',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='citeertitel',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='titel',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='persoon',
            name='titels',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zaak',
            name='titel',
            field=models.TextField(blank=True, null=True),
        ),
    ]
