# Generated by Django 3.0.6 on 2020-05-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_db', '0002_auto_20200517_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='saved',
            field=models.BooleanField(default=False),
        ),
    ]
