# Generated by Django 3.0.6 on 2020-05-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_db', '0003_entry_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='next',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
