# Generated by Django 3.1.5 on 2021-01-17 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sync_db', '0003_auto_20210117_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fractiezetelpersoon',
            name='fractie',
        ),
    ]
