# Generated by Django 3.0.6 on 2020-06-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_db', '0003_auto_20200601_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persoonloopbaan',
            name='tot_en_met',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='persoonloopbaan',
            name='van',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='persoonnevenfunctie',
            name='periode_tot_en_met',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='persoonnevenfunctie',
            name='periode_van',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='persoononderwijs',
            name='tot_en_met',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='persoononderwijs',
            name='van',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
