# Generated by Django 3.1.5 on 2021-01-17 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sync_db', '0004_remove_fractiezetelpersoon_fractie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persoonnevenfunctieinkomsten',
            old_name='nevenfunctie',
            new_name='persoon_nevenfunctie',
        ),
    ]
