# Generated by Django 3.0.6 on 2020-06-01 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sync_db', '0004_auto_20200601_1321'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kamerstukdossie',
            new_name='Kamerstukdossier',
        ),
    ]
