# Generated by Django 3.0.6 on 2020-06-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_db', '0005_auto_20200601_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persoonnevenfunctieinkomsten',
            name='bedrag',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
    ]
