# Generated by Django 3.0.6 on 2020-06-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_db', '0009_auto_20200602_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zaak',
            name='afgedaan',
            field=models.NullBooleanField(default=None),
        ),
    ]
