# Generated by Django 3.0.6 on 2020-06-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_db', '0010_auto_20200602_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kamerstukdossier',
            name='afgesloten',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='stemming',
            name='vergissing',
            field=models.NullBooleanField(default=None),
        ),
    ]
