# Generated by Django 3.0.6 on 2020-06-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_db', '0014_auto_20200604_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zaak',
            name='onderwerp',
            field=models.TextField(blank=True, null=True),
        ),
    ]
