# Generated by Django 3.0.6 on 2020-07-03 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sync_db', '0016_buggedmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BuggedModel',
        ),
    ]
