# Generated by Django 3.0.8 on 2020-07-31 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sync_db', '0019_besluit_zaak'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zaak',
            old_name='grodnslag_voorhang',
            new_name='grondslagvoorhang',
        ),
    ]
